language: objective-c
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec pod install --repo-update
cache:
  - bundler
  - cocoapods
language: objective-c
osx_image: xcode10
xcode_project: GameCaro.xcworkspace
xcode_scheme: DEV
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
before_script:
  - chmod +x ./scripts/add-key.sh
  - sh ./scripts/add-key.sh
script:
  - ./scripts/linter
  - xcodebuild clean build -sdk iphonesimulator -workspace GameCaro.xcworkspace -scheme DEV
  - if [[ "$TRAVIS_BRANCH" == "develop" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then bundle exec fastlane deploy_dev_gamecaro; fi
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then bundle exec fastlane deploy_dev_gamecaro; fi
  - if [[ "$TRAVIS_BRANCH" =~ "release"* && "$TRAVIS_PULL_REQUEST" == "false" ]]; then bundle exec fastlane deploy_dev_gamecaro; fi
install:
  - set -o pipefail
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh