language: objective-c
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec pod install --repo-update
cache:
  - bundler
  - cocoapods
language: objective-c
osx_image: xcode10
xcode_project: GameCaro.xcworkspace
xcode_scheme: GameCaro-Dev
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
before_script:
  - chmod +x ./scripts/add-key.sh
  - sh ./scripts/add-key.sh
script:
  - ./scripts/linter
  - bundle exec fastlane deploy_dev_gamecaro
install:
  - set -o pipefail
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh